### ISSUE TITLE
create a mailchimp

### ISSUE THREAD

**Issue by jungeebah** [jungeebah/herekochu#29]
Create a mailchimp account

**Comment by jungeebah** [comment]
once done do update _config.yml from the master branch for mailchimp setting
``` yml
# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f
```
