### ISSUE TITLE
clean up _config.yml

### ISSUE THREAD

**Issue by jungeebah** [jungeebah/herekochu#42]
``` yaml
# Author settings
author:
  - name: Daami Review Team
    bio: Daami Review website provides review of movies.
    url: https://www.daamireview.com/

social:
  - name: Twitter
    url: https://twitter.com/DaamiReview
  - name: Instagram
    url: https://www.instagram.com/daamireview/
  - name: Facebook
    url: https://www.facebook.com/daami.review.3
  - name: YouTube
    url: https://www.youtube.com/channel/UC_0ezAIoT768C1C_Xa2IeWw/
  - name: Codepen
    url: https://codepen.io/daamireview

```
