### ISSUE TITLE
Set a fix template for review post page

### ISSUE THREAD

**Issue by jungeebah** [jungeebah/herekochu#68]
Need to describe a fixed base template for the review page. As this is the most import section of our website

**Comment by jungeebah** [comment]
this is related with #1

**Comment by jungeebah** [comment]
i made some changes to the template to match the display feature. the change is in the development branch for someone to look at the code. One example is 
```yaml
layout: post
title: "Rashomon"
date: 2020-05-03
language: Japanese
description: First review
movie:
  rating: M
  director: Someone
  Starring: this,that,him/her,who knows
  Writer: who knows
  genre: 
    - Drama
    - Crime
rating: 9.5
image: /assets/images/Rashomon.jpg
author: Jungee
tags:
  - Japenese
  - Foreign
```

**Comment by jungeebah** [comment]
Need an active reviewing of this thing as this is a blockage to so many things

**Comment by jungeebah** [comment]
```yaml
layout: post
title: "Rashomon"
date: 2020-05-03
language: Japanese
description: First review
movie:
  rating: M
  director: Someone
  Starring: this,that,him/her,who knows
  Writer: who knows
  genre: 
    - Drama
    - Crime
rating: 9.5
image: /assets/images/Rashomon.jpg
author: Jungee
tags:
  - Japanese
  - Foreign
  - Drama
  - Crime
```

As a hack the genre and language has to be included in tags so that we can automatically generate a tagged page. This is a redundancy which will need some code adjustment in future.

**Comment by jungeebah** [comment]
agadhi ko display ma need to make use of the description rather than the first 35 words of the content. This way the display will be more structured.

**Comment by jungeebah** [comment]
<img width="1265" alt="Screen Shot 2020-06-05 at 12 58 18 PM" src="https://user-images.githubusercontent.com/55767005/83917734-3c486b00-a72c-11ea-9977-3a70a3da6b1e.png">

**Comment by jungeebah** [comment]
```yaml
---
layout: post
title: "Tumbbad"
rating: 9.0
language: Hindi
Spoiler: true
movie:
  genre: 
    - Drama
    - Crime
  length : 104 min
  rating: M
  Box-office: Hit
cast-crew:
  director: Rahi Anil Barve
  creative-director: Anand Gandhi
  co-director: Adesh Prasad
  Starring: 
    - Sohum Shah 
    - Jyoti Malshe 
    - Anita Date
    - Rojini Chakraborty
    - Deepak Damle
  Writer: 
    - Mitesh Shah
    - Rahi Anil Barve
    - Adesh Prasad
    - Anand Gandhi
    - Narayan Dharap
date: 2020-05-19
description: Human lust and it's tragedy
image: /assets/images/Tumbbad.jpg
author: dasol
tags:
  - Hindi
  - Foreign
  - Drama
  - Crime
---
```
latest template used
