### ISSUE TITLE
Submit Weekly Movie Reviews 

### ISSUE THREAD

**Issue by prohyp** [jungeebah/herekochu#75]
Submit 5 new movie reviews by end of week 6/7/2020.

**Comment by adrinz** [comment]
We need to finalize the template for the review page before we start submitting movie reviews.

**Comment by dasol1985** [comment]
Agree with Biwash


Sent from Yahoo Mail for iPhone


On Tuesday, June 2, 2020, 8:26 PM, Biwash Shrestha <notifications@github.com> wrote:




We need to finalize the template for the review page before we start submitting movie reviews.

**Comment by jungeebah** [comment]
this is the template I am using for testing
```yaml
movie:
  rating: M
  director: Someone
  Starring: this,that,him/her,who knows
  Writer: who knows
  language: Japanese
  genre: 
    - Drama
    - Crime
```

**Comment by jungeebah** [comment]
full
```yaml
layout: post
title: "Rashomon"
date: 2020-05-03
description: First review
movie:
  rating: M
  director: Someone
  Starring: this,that,him/her,who knows
  Writer: who knows
  language: Japanese
  genre: 
    - Drama
    - Crime
rating: 9.5
image: /assets/images/Rashomon.jpg
author: Jungee
tags:
  - Japenese
  - Foreign
```
